"use client";
import { useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
export default function DateRangeControls({ todayIso, monthStartIso, lastMonthStartIso, lastMonthEndIso, quarterStartIso, quarterEndIso, fromIso, toIso }: { todayIso: string; monthStartIso: string; lastMonthStartIso: string; lastMonthEndIso: string; quarterStartIso: string; quarterEndIso: string; fromIso: string; toIso: string }) {
 const router=useRouter(); const params=useSearchParams(); const [from,setFrom]=useState(fromIso); const [to,setTo]=useState(toIso);
 function setRange(nextFrom:string,nextTo:string,preset:string){const next=new URLSearchParams(params.toString());next.set("from",nextFrom);next.set("to",nextTo);next.set("preset",preset);router.push("/dashboard?"+next.toString());}
 return <section aria-label="Reporting date range" className="co-card p-4"><div className="flex flex-wrap gap-2"><Button type="button" onClick={()=>setRange(monthStartIso,todayIso,"this_month")} className="min-h-11">This month</Button><Button type="button" variant="outline" onClick={()=>setRange(lastMonthStartIso,lastMonthEndIso,"last_month")} className="min-h-11">Last month</Button><Button type="button" variant="outline" onClick={()=>setRange(quarterStartIso,quarterEndIso,"quarter")} className="min-h-11">Q{Math.floor((Number(todayIso.slice(5,7))-1)/3)+1}</Button><Button type="button" variant="outline" onClick={()=>setRange(from,to,"custom")} className="min-h-11">Custom range</Button></div><div className="mt-3 flex flex-wrap gap-2"><label className="grid gap-1 text-xs"><span>From</span><Input type="date" value={from} onChange={(event)=>setFrom(event.target.value)} className="min-h-11" /></label><label className="grid gap-1 text-xs"><span>Through</span><Input type="date" value={to} onChange={(event)=>setTo(event.target.value)} className="min-h-11" /></label><Button type="button" variant="outline" onClick={()=>setRange(from,to,"custom")} className="min-h-11 self-end">Apply custom range</Button></div></section>;
}
