"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";

export default function LoginPage() {
  const router = useRouter();
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(false);
  async function handleSubmit(event: React.FormEvent) { event.preventDefault(); setLoading(true); setError(null); const { error: signInError } = await createClient().auth.signInWithPassword({ email, password }); if (signInError) { setError(signInError.message); setLoading(false); return; } router.push("/dashboard"); router.refresh(); }
  return <main className="min-h-screen bg-[var(--co-cream)] px-4 py-8 text-[var(--co-ink)] sm:px-8"><div className="mx-auto grid min-h-[calc(100vh-4rem)] max-w-6xl items-center gap-10 lg:grid-cols-[1.05fr_0.95fr]"><section className="hidden min-h-[620px] overflow-hidden rounded-[2rem] bg-[var(--co-evergreen)] p-10 text-white shadow-[0_24px_80px_rgba(20,33,31,.16)] lg:flex lg:flex-col lg:justify-between"><div><div className="flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-2xl bg-[var(--co-accent)] text-sm font-black text-[var(--co-evergreen)]">CO</span><span className="text-xl font-semibold">CleanOps</span></div><p className="mt-20 max-w-md text-6xl font-semibold leading-[0.96] tracking-[-0.07em]">The calm center of your cleaning operation.</p><p className="mt-6 max-w-md text-base leading-7 text-white/65">Schedule the work, keep customer details close, reconcile payments, and prepare payroll from one operating desk.</p></div><div className="grid grid-cols-3 gap-3"><Mini label="Schedule" value="Clear" /><Mini label="Payments" value="Tracked" /><Mini label="Payroll" value="Ready" /></div></section><section className="mx-auto w-full max-w-md"><div className="mb-10 lg:hidden"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-2xl bg-[var(--co-evergreen)] text-sm font-black text-[var(--co-accent)]">CO</span><span className="text-xl font-semibold">CleanOps</span></div></div><p className="eyebrow">Operations desk</p><h1 className="mt-3 text-4xl font-semibold tracking-[-0.05em]">Welcome back.</h1><p className="mt-3 text-sm leading-6 text-[var(--co-muted)]">Sign in to manage today&apos;s schedule, customers, jobs, invoices, and payroll.</p><form onSubmit={handleSubmit} className="mt-8 space-y-5"><label className="block text-sm"><span className="mb-2 block text-xs font-semibold text-[var(--co-muted)]">Email address</span><input id="email" type="email" required value={email} onChange={(event) => setEmail(event.target.value)} className="co-input w-full bg-white py-3" placeholder="you@company.com" /></label><label className="block text-sm"><span className="mb-2 block text-xs font-semibold text-[var(--co-muted)]">Password</span><input id="password" type="password" required value={password} onChange={(event) => setPassword(event.target.value)} className="co-input w-full bg-white py-3" placeholder="Your password" /></label>{error && <p role="alert" className="rounded-xl bg-rose-50 px-3 py-2 text-sm text-rose-700">{error}</p>}<button type="submit" disabled={loading} className="co-button-primary w-full justify-center py-3">{loading ? "Signing in…" : "Sign in →"}</button></form><p className="mt-8 text-xs leading-5 text-[var(--co-muted)]">CleanOps is an internal operations workspace. Customer-facing proposals use a separate secure link.</p></section></div></main>;
}

function Mini({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl border border-white/10 bg-white/5 p-3"><p className="text-[10px] uppercase tracking-[0.15em] text-white/45">{label}</p><p className="mt-2 text-sm font-semibold text-[var(--co-accent)]">{value}</p></div>; }
