import { and, eq, gte, inArray, lt, ne, sql } from "drizzle-orm";
import { db } from "@/db";
import { companies, customers, ghlSyncLog, invoices, jobAssignments, jobs, quotes, users } from "@/db/schema";
import { overdueSqlCondition } from "@/lib/invoices/overdue";
import type { DashboardRange, ExceptionCounts, PulseMetrics, TodayRun } from "./types";
const n = (value: unknown) => Number(value ?? 0);
export async function getTodaysRun(companyId: string, todayIso: string): Promise<TodayRun> {
  const rows = await db.select({ id: jobs.id, status: jobs.status, type: jobs.type, scheduledStartTime: jobs.scheduledStartTime, firstName: customers.firstName, lastName: customers.lastName, address: customers.addressLine1, city: customers.city }).from(jobs).innerJoin(customers, eq(jobs.customerId, customers.id)).where(and(eq(jobs.companyId, companyId), eq(customers.companyId, companyId), eq(jobs.scheduledDate, todayIso))).orderBy(jobs.scheduledStartTime);
  const assignments = rows.length ? await db.select({ jobId: jobAssignments.jobId, firstName: users.firstName, lastName: users.lastName }).from(jobAssignments).innerJoin(users, eq(jobAssignments.userId, users.id)).innerJoin(jobs, eq(jobAssignments.jobId, jobs.id)).where(and(eq(jobs.companyId, companyId), eq(users.companyId, companyId), inArray(jobAssignments.jobId, rows.map((row) => row.id)))) : [];
  const byJob = new Map<string, string[]>(); assignments.forEach((row) => byJob.set(row.jobId, [...(byJob.get(row.jobId) ?? []), row.firstName + " " + row.lastName]));
  const now = new Date().toLocaleTimeString("en-GB", { hour: "2-digit", minute: "2-digit", hour12: false });
  const jobsView = rows.map((row) => ({ id: row.id, status: row.status, type: row.type, scheduledStartTime: row.scheduledStartTime, customerName: row.firstName + " " + row.lastName, address: [row.address, row.city].filter(Boolean).join(", ") || "Address not set", assignedTo: byJob.get(row.id) ?? [] }));
  return { jobs: jobsView, scheduled: rows.filter((row) => row.status === "scheduled").length, completed: rows.filter((row) => row.status === "completed").length, atRisk: jobsView.filter((job) => job.assignedTo.length === 0 || (job.status === "scheduled" && Boolean(job.scheduledStartTime && job.scheduledStartTime.slice(0, 5) < now))).length };
}
export async function getExceptionCounts(companyId: string, todayIso: string): Promise<ExceptionCounts> {
  const [jobRows, customerRows, syncRows, companyRows] = await Promise.all([
    db.select({ unassigned: sql<number>`count(*) filter (where not exists (select 1 from job_assignments ja where ja.job_id = ${jobs.id}))`, missingHours: sql<number>`count(*) filter (where ${jobs.status} = 'completed' and not exists (select 1 from time_entries te where te.job_id = ${jobs.id}))`, awaitingInvoice: sql<number>`count(*) filter (where ${jobs.status} = 'completed' and not exists (select 1 from invoices i where i.job_id = ${jobs.id} and i.company_id = ${companyId}))` }).from(jobs).where(and(eq(jobs.companyId, companyId), eq(jobs.scheduledDate, todayIso))),
    db.select({ paymentMethod: sql<number>`count(*) filter (where ${customers.isArchived} = false and (${customers.paymentMethods} is null or cardinality(${customers.paymentMethods}) = 0))`, incompleteNotes: sql<number>`count(*) filter (where ${customers.isArchived} = false and (${customers.addressLine1} is null or ${customers.addressLine1} = '' or ${customers.generalNotes} is null or trim(${customers.generalNotes}) = '' or ${customers.gateCodeOrKeyNotes} is null or trim(${customers.gateCodeOrKeyNotes}) = ''))` }).from(customers).where(eq(customers.companyId, companyId)),
    db.select({ count: sql<number>`count(*)` }).from(ghlSyncLog).where(and(eq(ghlSyncLog.companyId, companyId), ne(ghlSyncLog.status, "ok"))),
    db.select({ settings: companies.settings }).from(companies).where(eq(companies.id, companyId)).limit(1),
  ]);
  const inventory = Array.isArray((companyRows[0]?.settings as { inventory?: unknown } | undefined)?.inventory) ? (companyRows[0]!.settings as { inventory: Array<{ onHand: number; reorderAt: number }> }).inventory : [];
  return { unassigned: n(jobRows[0]?.unassigned), missingHours: n(jobRows[0]?.missingHours), awaitingInvoice: n(jobRows[0]?.awaitingInvoice), paymentMethod: n(customerRows[0]?.paymentMethod), incompleteNotes: n(customerRows[0]?.incompleteNotes), sync: n(syncRows[0]?.count), lowSupplies: inventory.filter((item) => item.onHand <= item.reorderAt).length };
}
export async function getPulseMetrics(companyId: string, range: DashboardRange): Promise<PulseMetrics> {
  const from = new Date(range.fromIso + "T00:00:00.000Z"); const to = new Date(range.toIso + "T00:00:00.000Z"); to.setUTCDate(to.getUTCDate() + 1); const previousFrom = new Date(range.prevFromIso + "T00:00:00.000Z"); const previousTo = new Date(range.prevToIso + "T00:00:00.000Z"); previousTo.setUTCDate(previousTo.getUTCDate() + 1);
  const [today, revenue, previous, conversion, collections] = await Promise.all([getTodaysRun(companyId, range.todayIso), db.select({ amount: sql<number>`coalesce(sum(${invoices.amountPaidCents}), 0)`, count: sql<number>`count(*)` }).from(invoices).where(and(eq(invoices.companyId, companyId), eq(invoices.status, "paid"), gte(invoices.paidAt, from), lt(invoices.paidAt, to))), db.select({ amount: sql<number>`coalesce(sum(${invoices.amountPaidCents}), 0)` }).from(invoices).where(and(eq(invoices.companyId, companyId), eq(invoices.status, "paid"), gte(invoices.paidAt, previousFrom), lt(invoices.paidAt, previousTo))), db.select({ sent: sql<number>`count(*) filter (where ${quotes.status} <> 'draft')`, accepted: sql<number>`count(*) filter (where ${quotes.status} = 'accepted')` }).from(quotes).where(and(eq(quotes.companyId, companyId), gte(quotes.createdAt, from), lt(quotes.createdAt, to))), db.select({ count: sql<number>`count(*)`, amount: sql<number>`coalesce(sum(greatest(${invoices.totalCents} - ${invoices.amountPaidCents}, 0)), 0)` }).from(invoices).where(and(eq(invoices.companyId, companyId), overdueSqlCondition()))]);
  return { jobsToday: { scheduled: today.scheduled, completed: today.completed, atRisk: today.atRisk }, revenue: { receivedCents: n(revenue[0]?.amount), previousCents: n(previous[0]?.amount), hasData: n(revenue[0]?.count) > 0 }, conversion: { sent: n(conversion[0]?.sent), accepted: n(conversion[0]?.accepted), hasData: n(conversion[0]?.sent) > 0 }, collections: { overdueCents: n(collections[0]?.amount), overdueCount: n(collections[0]?.count) } };
}
