"use client";

import { useEffect, useState } from "react";

type Employee = { id: string; firstName: string; lastName: string; isActive: boolean };
type Event = { id: string; title: string; scheduledDate: string; isAllDay: boolean; startTime: string | null; durationMinutes: number | null; employeeIds: string[] };

export default function CalendarEventsStrip({ dayIso, employees }: { dayIso: string; employees: Employee[] }) {
  const [events, setEvents] = useState<Event[]>([]); const [open, setOpen] = useState(false); const [title, setTitle] = useState(""); const [allDay, setAllDay] = useState(true); const [startTime, setStartTime] = useState("09:00"); const [durationMinutes, setDurationMinutes] = useState(60); const [employeeIds, setEmployeeIds] = useState<string[]>([]); const [error, setError] = useState("");
  async function load() { const response = await fetch(`/api/calendar-events?start=${dayIso}&end=${dayIso}`, { cache: "no-store" }); const body = await response.json().catch(() => ({})); if (response.ok) setEvents(body.events ?? []); }
  // eslint-disable-next-line react-hooks/set-state-in-effect -- load resolves asynchronously.
  useEffect(() => { void load(); }, [dayIso]);
  async function save() { const response = await fetch("/api/calendar-events", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ title, scheduledDate: dayIso, isAllDay: allDay, startTime: allDay ? null : startTime, durationMinutes: allDay ? null : durationMinutes, employeeIds }) }); const body = await response.json().catch(() => ({})); if (!response.ok) return setError(body.error?.formErrors?.[0] ?? "Could not add event."); setTitle(""); setEmployeeIds([]); setOpen(false); await load(); }
  return <div className="border-b border-[var(--co-line-soft)] bg-[var(--co-surface-muted)]/60 px-4 py-3"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex flex-wrap gap-2">{events.map((event) => <span key={event.id} className="co-badge-spark rounded-md px-2 py-1 text-xs font-semibold">{event.isAllDay ? "All day" : event.startTime?.slice(0, 5)} · {event.title}</span>)}{events.length === 0 ? <span className="text-xs text-[var(--co-muted)]">No internal events</span> : null}</div><button type="button" onClick={() => setOpen((value) => !value)} className="co-button-secondary px-3 py-2 text-xs">{open ? "Close" : "Add event"}</button></div>{open ? <form className="mt-3 grid gap-3 border-t border-[var(--co-line-soft)] pt-3 sm:grid-cols-2" onSubmit={(event) => { event.preventDefault(); void save(); }}><label className="text-xs font-semibold text-[var(--co-muted)]">Title<input required value={title} onChange={(event) => setTitle(event.target.value)} className="co-input mt-1 w-full" placeholder="Training, meeting, reminder" /></label><label className="flex items-end gap-2 pb-2 text-sm"><input type="checkbox" checked={allDay} onChange={(event) => setAllDay(event.target.checked)} />All day</label>{!allDay ? <><label className="text-xs font-semibold text-[var(--co-muted)]">Start<input type="time" value={startTime} onChange={(event) => setStartTime(event.target.value)} className="co-input mt-1 w-full" /></label><label className="text-xs font-semibold text-[var(--co-muted)]">Duration<select value={durationMinutes} onChange={(event) => setDurationMinutes(Number(event.target.value))} className="co-input mt-1 w-full"><option value={30}>30 min</option><option value={60}>1 hour</option><option value={120}>2 hours</option></select></label></> : null}<fieldset className="sm:col-span-2"><legend className="text-xs font-semibold text-[var(--co-muted)]">Employees</legend><div className="mt-1 flex flex-wrap gap-2">{employees.filter((employee) => employee.isActive).map((employee) => <label key={employee.id} className="flex items-center gap-1 text-xs"><input type="checkbox" checked={employeeIds.includes(employee.id)} onChange={() => setEmployeeIds((current) => current.includes(employee.id) ? current.filter((id) => id !== employee.id) : [...current, employee.id])} />{employee.firstName}</label>)}</div></fieldset>{error ? <p role="alert" className="text-xs text-[var(--co-danger)]">{error}</p> : null}<button className="co-button-primary justify-center sm:col-span-2" type="submit">Save event</button></form> : null}</div>;
}
