"use client";

import type { CalendarEmployee, CalendarJob } from "./page";
import { displayCustomer, employeeCardStyle, employeeColor, minutesFromTime } from "./shared";

const START = 9 * 60;
const TOTAL = 9 * 60;

export default function StaffVerticalBoard({ employees, jobs }: { employees: CalendarEmployee[]; jobs: CalendarJob[] }) {
  const active = employees.filter((employee) => employee.isActive);

  return <section className="overflow-hidden border border-[var(--co-line)] bg-[var(--co-surface)]"><div className="flex items-center justify-between border-b border-[var(--co-line-soft)] px-4 py-3"><div><h2 className="text-base font-semibold">Staff Vertical</h2><p className="mt-0.5 text-xs text-[var(--co-muted)]">Each cleaner is a row. Time runs left to right.</p></div><span className="text-xs font-medium text-[var(--co-muted)]">Scroll horizontally for the full day</span></div><div className="overflow-x-auto"><div className="min-w-[980px]"><div className="grid border-b border-[var(--co-line-soft)]" style={{ gridTemplateColumns: "170px 1fr" }}><div className="bg-[var(--co-surface-muted)] px-3 py-2 text-xs font-semibold">Cleaner</div><div className="grid bg-[var(--co-surface-muted)] text-xs font-semibold text-[var(--co-muted)]" style={{ gridTemplateColumns: "repeat(9, minmax(90px, 1fr))" }}>{Array.from({ length: 9 }, (_, index) => <span key={index} className="border-l border-[var(--co-line-soft)] px-2 py-2">{index + 9}:00</span>)}</div></div>{active.map((employee) => { const assigned = jobs.filter((job) => job.assignedUserIds.includes(employee.id)); return <div key={employee.id} className="grid min-h-20 border-b border-[var(--co-line-soft)]" style={{ gridTemplateColumns: "170px 1fr" }}><div className="flex items-center gap-2 bg-[var(--co-surface-muted)]/60 px-3 text-sm font-semibold"><span className="h-2.5 w-2.5 rounded-full" style={{ background: employeeColor(employee.id) }} />{employee.firstName} {employee.lastName}</div><div className="relative bg-white" style={{ backgroundImage: "linear-gradient(to right, var(--co-line-soft) 1px, transparent 1px)", backgroundSize: "11.111% 100%" }}>{assigned.map((job) => { const start = Math.max(0, Math.min(TOTAL, minutesFromTime(job.scheduledStartTime) - START)); const duration = Math.max(45, job.estimatedDurationMinutes ?? 75); return <a key={job.id} href={`/jobs/${job.id}`} className="absolute top-2 bottom-2 overflow-hidden rounded-md border px-2 py-1 text-xs font-semibold text-[var(--co-ink)] hover:brightness-95" style={{ left: `${(start / TOTAL) * 100}%`, width: `${Math.min(100 - (start / TOTAL) * 100, (duration / TOTAL) * 100)}%`, ...employeeCardStyle(employee.id) }}>{job.scheduledStartTime?.slice(0, 5) ?? "No time"} · {displayCustomer(job)}</a>; })}</div></div>; })}</div></div></section>;
}
